defaults:
  - optimizer: sgd
  - scheduler: step_lr
  - aug:

exp_name: coco_training

hydra:
  run:
    dir: ./run/${now:%Y-%m-%d}/${now:%H-%M-%S}_${exp_name}

dataset:
  filter_labels: # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: val_loss
  mode: min
  save_top_k: 1
  dirpath: checkpoint
  save_last: true
  filename: ckp_{epoch:d}-{step:d}-{val_loss:.3f}

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: ${checkpoint.monitor}
  min_delta: 0.002
  patience: 30
  divergence_threshold: 5.0
  mode: ${checkpoint.mode}

trainer:
  max_epochs: 50
  gpus: [0, 1]
  strategy: ddp
  gradient_clip_val: 10.0
  precision: 16
  accelerator: null
  num_sanity_val_steps: 0

logger:
  mlflow: False
  experiment_name: ${exp_name}
  server_address: http://192.168.3.78:5000
